globalVariables(c(
  "x_plot", "group", "value", "which_distance", "bin", "kmer", "facet_location", "candidate_pattern", "candidate_kmer"
))

# Internal: columns generated by posMatchR annotation/matching steps.
.posmatchr_annotation_cols <- function() {
  c(
    "location", "feature", "region_class", "gene_id", "tx_id", "tx_name",
    "tx_len", "cds_len", "utr5_len", "utr3_len", "intron_len", "n_intron",
    "nexon", "feature_len", "feature_prop", "metagene_prop",
    "metagene_split", "metagene_split3", "isoform_weight", "feature_width",
    "segment_rank", "dist_from_feature_start", "dist_from_feature_end",
    "start_dist", "stop_dist", "start_dist_tx", "stop_dist_tx", "tx_pos", "dist_to_tx_start",
    "dist_to_tx_end", "nearest_exon_junction_dist",
    "gene_symbol", "gene_name"
  )
}

.posmatchr_match_cols <- function() {
  c(
    "is_positive", "matched_negative_id", "matched_positive_id",
    "is_matched_negative", "meta_delta", "match_set",
    "loc_fiveUTR", "loc_coding", "loc_threeUTR"
  )
}

.drop_mcols <- function(gr, cols) {
  mc <- S4Vectors::mcols(gr)
  hit <- intersect(cols, colnames(mc))
  if (length(hit)) {
    for (nm in hit) mc[[nm]] <- NULL
    S4Vectors::mcols(gr) <- mc
  }
  gr
}

.coordinate_site_id <- function(gr, strand = TRUE) {
  if (strand) {
    paste0(
      as.character(GenomicRanges::seqnames(gr)), ":",
      GenomicRanges::start(gr), ":",
      as.character(GenomicRanges::strand(gr))
    )
  } else {
    paste0(
      as.character(GenomicRanges::seqnames(gr)), ":",
      GenomicRanges::start(gr)
    )
  }
}

.normalise_binary_label <- function(x, strict = TRUE) {
  if (is.logical(x)) x <- as.integer(x)
  if (is.factor(x)) x <- as.character(x)
  if (is.character(x)) {
    ok <- is.na(x) | x %in% c("0", "1")
    if (all(ok)) x <- as.integer(x)
  }
  if (!is.integer(x)) x <- suppressWarnings(as.integer(x))
  if (strict && any(!is.na(x) & !(x %in% c(0L, 1L)))) {
    stop("Labels must be 0/1, logical, or character/factor values '0'/'1'.")
  }
  x
}

#' Prepare a single-nucleotide GRanges object
#'
#' Normalises a user-supplied \code{GRanges} for posMatchR. The function enforces
#' single-nucleotide ranges, creates stable site identifiers, and optionally sets a
#' binary label column. Arbitrary existing metadata are preserved by default.
#'
#' @param gr A \code{GRanges}.
#' @param label Optional scalar or vector of 0/1 labels to write to \code{label_col}.
#' @param label_col Metadata column used for labels.
#' @param site_id_col Metadata column used for stable site identifiers.
#' @param width_action Either \code{"resize"} or \code{"error"} when ranges are not width 1.
#' @param strip_mcols If TRUE, remove existing metadata before writing site IDs/labels.
#' @param strand_in_id If TRUE, include strand in generated coordinate IDs.
#'
#' @return A single-nucleotide \code{GRanges}.
#' @export
prepare_sites <- function(gr,
                          label = NULL,
                          label_col = "label",
                          site_id_col = "site_id",
                          width_action = c("resize", "error"),
                          strip_mcols = FALSE,
                          strand_in_id = TRUE) {
  width_action <- match.arg(width_action)
  if (!inherits(gr, "GRanges")) stop("`gr` must be a GRanges.")

  if (any(GenomicRanges::width(gr) != 1L)) {
    if (width_action == "error") {
      stop("All ranges must have width 1. Use width_action='resize' to coerce point sites.")
    }
    warning("Some ranges have width != 1. Resizing to width 1 with fix='center'.")
    gr <- IRanges::resize(gr, width = 1L, fix = "center")
  }

  if (strip_mcols) {
    S4Vectors::mcols(gr) <- S4Vectors::DataFrame()
  }

  mc <- S4Vectors::mcols(gr)

  ids <- NULL
  if (site_id_col %in% colnames(mc)) {
    ids <- as.character(mc[[site_id_col]])
  } else if (!is.null(names(gr))) {
    ids <- as.character(names(gr))
  }
  if (is.null(ids) || length(ids) != length(gr)) {
    ids <- .coordinate_site_id(gr, strand = strand_in_id)
  }
  bad <- is.na(ids) | !nzchar(ids)
  if (any(bad)) ids[bad] <- .coordinate_site_id(gr[bad], strand = strand_in_id)
  ids <- make.unique(ids, sep = "_")

  mc[[site_id_col]] <- ids
  if (!is.null(label)) {
    if (length(label) == 1L && length(gr) != 1L) label <- rep(label, length(gr))
    if (length(label) != length(gr)) {
      stop("`label` must be length 1 or length(gr).")
    }
    mc[[label_col]] <- .normalise_binary_label(label, strict = TRUE)
  } else if (label_col %in% colnames(mc)) {
    y0 <- mc[[label_col]]
    y1 <- .normalise_binary_label(y0, strict = FALSE)
    ok <- is.na(y1) | y1 %in% c(0L, 1L)
    if (all(ok)) mc[[label_col]] <- y1
  }

  S4Vectors::mcols(gr) <- mc
  names(gr) <- ids
  gr
}

.validate_sites_gr <- function(gr, label_col = "label") {
  prepare_sites(gr, label = NULL, label_col = label_col, strip_mcols = FALSE)
}

.validate_input_gr <- function(gr, label_col = "label", require_both = TRUE) {
  if (!inherits(gr, "GRanges")) stop("`gr` must be a GRanges.")
  if (!(label_col %in% colnames(S4Vectors::mcols(gr)))) {
    stop("`gr` must contain metadata column `", label_col, "`.")
  }
  gr <- prepare_sites(gr, label = NULL, label_col = label_col, strip_mcols = FALSE)
  y <- .normalise_binary_label(S4Vectors::mcols(gr)[[label_col]], strict = TRUE)
  S4Vectors::mcols(gr)[[label_col]] <- y
  if (require_both) {
    if (sum(y == 1L, na.rm = TRUE) < 1L) stop("No positives found (", label_col, " == 1).")
    if (sum(y == 0L, na.rm = TRUE) < 1L) stop("No negatives found (", label_col, " == 0).")
  }
  gr
}

.map_to_target_seqlevels <- function(requested, target) {
  requested <- unique(as.character(requested))
  requested <- requested[!is.na(requested) & nzchar(requested)]
  target <- as.character(target)

  out <- requested
  ok <- out %in% target

  idx <- which(!ok)
  if (length(idx)) {
    cand <- paste0("chr", out[idx])
    m <- match(cand, target)
    hit <- !is.na(m)
    if (any(hit)) {
      out[idx[hit]] <- target[m[hit]]
      ok[idx[hit]] <- TRUE
    }
  }

  idx <- which(!ok)
  if (length(idx)) {
    cand <- paste0("Chr", out[idx])
    m <- match(cand, target)
    hit <- !is.na(m)
    if (any(hit)) {
      out[idx[hit]] <- target[m[hit]]
      ok[idx[hit]] <- TRUE
    }
  }

  idx <- which(!ok)
  if (length(idx)) {
    cand <- sub("^chr", "", out[idx], ignore.case = TRUE)
    m <- match(cand, target)
    hit <- !is.na(m)
    if (any(hit)) {
      out[idx[hit]] <- target[m[hit]]
      ok[idx[hit]] <- TRUE
    }
  }

  idx <- which(!ok)
  if (length(idx)) {
    m <- match(tolower(out[idx]), tolower(target))
    hit <- !is.na(m)
    if (any(hit)) {
      out[idx[hit]] <- target[m[hit]]
      ok[idx[hit]] <- TRUE
    }
  }

  list(mapped = unique(out[ok]), dropped = unique(out[!ok]))
}

.harmonize_seqlevels <- function(gr,
                                 txdb,
                                 seqstyle = NULL,
                                 chrs = NULL,
                                 pruning.mode = "coarse") {
  if (!inherits(gr, "GRanges")) stop("`gr` must be a GRanges.")

  txdb_ref <- txdb
  txdb <- txdb_ref

  if (!is.null(seqstyle)) {
    suppressWarnings(try(GenomeInfoDb::seqlevelsStyle(gr) <- seqstyle, silent = TRUE))
    suppressWarnings(try(GenomeInfoDb::seqlevelsStyle(txdb) <- seqstyle, silent = TRUE))
  } else {
    st <- tryCatch(GenomeInfoDb::seqlevelsStyle(txdb), error = function(e) character(0))
    if (length(st)) {
      suppressWarnings(try(GenomeInfoDb::seqlevelsStyle(gr) <- st[1], silent = TRUE))
    }
  }

  if (!is.null(chrs)) {
    gr <- .rename_seqlevels_to_target(gr, chrs, pruning.mode = pruning.mode)
    txdb <- .rename_seqlevels_to_target(txdb, chrs, pruning.mode = pruning.mode)
  } else {
    direct_common <- intersect(GenomeInfoDb::seqlevels(gr), GenomeInfoDb::seqlevels(txdb))
    if (!length(direct_common)) {
      gr <- .rename_seqlevels_to_target(gr, GenomeInfoDb::seqlevels(txdb), pruning.mode = pruning.mode)
    }
  }

  gr_levels <- GenomeInfoDb::seqlevels(gr)
  tx_levels <- GenomeInfoDb::seqlevels(txdb)
  if (!length(tx_levels)) {
    stop("`txdb` has no seqlevels. Reload/recreate the TxDb and retry.")
  }

  if (is.null(chrs)) {
    chrs_final <- intersect(gr_levels, tx_levels)
    dropped <- setdiff(unique(as.character(GenomicRanges::seqnames(gr))), chrs_final)
  } else {
    mapped_to_tx <- .map_to_target_seqlevels(chrs, tx_levels)
    chrs_final <- intersect(mapped_to_tx$mapped, gr_levels)

    # If seqlevel styles still differ after the style coercion above, try one more
    # direct remapping of the user-requested names to the site object. This keeps
    # useful warning messages while avoiding silent loss of canonical chromosomes.
    if (!length(chrs_final)) {
      mapped_to_gr <- .map_to_target_seqlevels(chrs, gr_levels)
      chrs_final <- intersect(mapped_to_gr$mapped, tx_levels)
    }

    dropped <- unique(c(mapped_to_tx$dropped, setdiff(mapped_to_tx$mapped, chrs_final)))
  }

  chrs_final <- unique(chrs_final[!is.na(chrs_final) & nzchar(chrs_final)])
  if (!length(chrs_final)) {
    stop(
      "No overlapping seqlevels between `gr` and `txdb` after harmonization.\n",
      "seqlevels(gr): ", paste(gr_levels, collapse = ", "), "\n",
      "seqlevels(txdb): ", paste(tx_levels, collapse = ", ")
    )
  }

  observed_before <- unique(as.character(GenomicRanges::seqnames(gr)))
  dropped_observed <- setdiff(observed_before, chrs_final)
  if (length(dropped_observed)) {
    warning(
      "Dropping site seqlevels not present in the selected TxDb/chrs: ",
      paste(dropped_observed, collapse = ", ")
    )
  }

  gr <- GenomeInfoDb::keepSeqlevels(gr, chrs_final, pruning.mode = pruning.mode)
  txdb <- GenomeInfoDb::keepSeqlevels(txdb, chrs_final, pruning.mode = pruning.mode)

  si <- GenomeInfoDb::seqinfo(txdb)
  common <- intersect(GenomeInfoDb::seqlevels(gr), names(si))
  if (length(common)) {
    try({
      GenomeInfoDb::seqinfo(gr) <- si[GenomeInfoDb::seqlevels(gr)]
    }, silent = TRUE)
  }
  gr <- suppressWarnings(GenomicRanges::trim(gr))

  list(
    gr = gr,
    txdb = txdb,
    chrs = chrs_final,
    dropped = unique(c(dropped, dropped_observed))
  )
}

.location_priority <- function(loc) {
  loc <- as.character(loc)
  pri <- rep.int(99L, length(loc))
  pri[loc == "coding"] <- 1L
  pri[loc == "fiveUTR"] <- 2L
  pri[loc == "threeUTR"] <- 3L
  pri[loc == "intron"] <- 4L
  pri[loc == "spliceSite"] <- 5L
  pri[loc == "promoter"] <- 6L
  pri[loc == "intergenic"] <- 7L
  pri[loc == "unannotated"] <- 100L
  pri
}

.map_location_to_feature <- function(location) {
  loc <- as.character(location)
  out <- rep.int("other", length(loc))
  out[loc == "coding"] <- "CDS"
  out[loc == "fiveUTR"] <- "5UTR"
  out[loc == "threeUTR"] <- "3UTR"
  out[loc == "intron"] <- "intron"
  out[loc == "intergenic"] <- "intergenic"
  out[loc == "spliceSite"] <- "spliceSite"
  out[loc == "promoter"] <- "promoter"
  out[loc == "unannotated"] <- "unannotated"
  out[is.na(loc) | !nzchar(loc)] <- "unannotated"
  out
}

.first_or_na <- function(x) {
  if (methods::is(x, "List") || is.list(x)) {
    return(vapply(x, function(z) {
      if (length(z) == 0L || all(is.na(z))) NA_character_ else as.character(z[[1L]])
    }, character(1)))
  }
  as.character(x)
}

.mcol_as_character <- function(x, n = NULL) {
  if (is.null(x)) return(rep(NA_character_, n %||% 0L))
  if (methods::is(x, "DNAStringSet") || methods::is(x, "AAStringSet")) return(as.character(x))
  if (methods::is(x, "List") || is.list(x)) {
    return(vapply(seq_along(x), function(i) {
      xi <- x[[i]]
      if (length(xi) == 0L || all(is.na(xi))) return(NA_character_)
      vals <- unique(as.character(xi[!is.na(xi)]))
      if (!length(vals)) NA_character_ else paste(vals, collapse = ",")
    }, character(1)))
  }
  as.character(x)
}

.mcol_as_numeric <- function(x, n = NULL) {
  if (is.null(x)) return(rep(NA_real_, n %||% 0L))
  if (methods::is(x, "List") || is.list(x)) {
    return(vapply(seq_along(x), function(i) {
      xi <- x[[i]]
      if (length(xi) == 0L || all(is.na(xi))) return(NA_real_)
      suppressWarnings(as.numeric(as.character(xi[[1L]])))
    }, numeric(1)))
  }
  suppressWarnings(as.numeric(as.character(x)))
}

`%||%` <- function(x, y) {
  if (is.null(x)) y else x
}

#' Add coordinate-derived IDs to a GRanges
#'
#' @param gr A \code{GRanges}.
#' @param strand If TRUE, include strand in the ID.
#' @param site_id_col Metadata column to update. Set NULL to update names only.
#'
#' @return The input \code{GRanges} with names, and optionally \code{site_id_col}, set.
#' @export
makeID <- function(gr, strand = TRUE, site_id_col = "site_id") {
  if (!inherits(gr, "GRanges")) stop("`gr` must be a GRanges.")
  ids <- .coordinate_site_id(gr, strand = strand)
  ids <- make.unique(ids, sep = "_")
  names(gr) <- ids
  if (!is.null(site_id_col)) S4Vectors::mcols(gr)[[site_id_col]] <- ids
  gr
}

#' Combine positive sites and candidate background sites
#'
#' Combines two \code{GRanges} objects into a single labelled object suitable for
#' \code{\link{annotate_sites}} followed by \code{\link{match_background}}.
#'
#' @param positives GRanges containing observed sites.
#' @param background GRanges containing candidate negative/background sites.
#' @param label_col Metadata column to create.
#' @param site_id_col Metadata site ID column.
#' @param positive_prefix Prefix added to generated positive IDs if needed.
#' @param background_prefix Prefix added to generated background IDs if needed.
#'
#' @return A labelled \code{GRanges}.
#' @export
combine_site_sets <- function(positives,
                              background,
                              label_col = "label",
                              site_id_col = "site_id",
                              positive_prefix = "pos_",
                              background_prefix = "bg_") {
  pos <- prepare_sites(positives, label = 1L, label_col = label_col, site_id_col = site_id_col)
  bg <- prepare_sites(background, label = 0L, label_col = label_col, site_id_col = site_id_col)

  pos_ids <- as.character(S4Vectors::mcols(pos)[[site_id_col]])
  bg_ids <- as.character(S4Vectors::mcols(bg)[[site_id_col]])

  if (length(intersect(pos_ids, bg_ids)) || anyDuplicated(c(pos_ids, bg_ids))) {
    pos_ids <- paste0(positive_prefix, make.unique(pos_ids, sep = "_"))
    bg_ids <- paste0(background_prefix, make.unique(bg_ids, sep = "_"))
    S4Vectors::mcols(pos)[[site_id_col]] <- pos_ids
    S4Vectors::mcols(bg)[[site_id_col]] <- bg_ids
    names(pos) <- pos_ids
    names(bg) <- bg_ids
  }

  c(pos, bg)
}

.seqlevel_candidates <- function(x) {
  x <- as.character(x)
  core <- sub("^(chr|Chr)", "", x, perl = TRUE)
  out <- c(x, core, paste0("chr", core), paste0("Chr", core))

  low <- tolower(core)
  if (low %in% c("m", "mt", "mitochondria", "mitochondrial", "chrm", "chrmt")) {
    out <- c(out, "M", "MT", "Mt", "chrM", "chrMT", "ChrM")
  }
  if (low %in% c("c", "pt", "cp", "chloroplast", "plastid", "chrc", "chrpt")) {
    out <- c(out, "C", "Pt", "PT", "Cp", "chrC", "chrPt", "ChrC", "ChrPt")
  }

  unique(out[!is.na(out) & nzchar(out)])
}

.make_seqlevel_rename_map <- function(from, target) {
  from <- as.character(from)
  target <- as.character(target)
  target <- target[!is.na(target) & nzchar(target)]
  new <- from
  matched <- rep(FALSE, length(from))

  if (!length(target) || !length(from)) {
    return(list(old = from, new = new, matched = matched))
  }

  target_lower <- tolower(target)
  for (i in seq_along(from)) {
    cand <- .seqlevel_candidates(from[i])
    m <- match(tolower(cand), target_lower)
    m <- m[!is.na(m)]
    if (length(m)) {
      new[i] <- target[m[1L]]
      matched[i] <- TRUE
    }
  }

  list(old = from, new = new, matched = matched)
}

.rename_seqlevels_to_target <- function(x, target, pruning.mode = "coarse") {
  target <- as.character(target)
  target <- target[!is.na(target) & nzchar(target)]
  if (!length(target)) return(x)

  old <- tryCatch(GenomeInfoDb::seqlevels(x), error = function(e) character(0))
  if (!length(old)) return(x)

  mp <- .make_seqlevel_rename_map(old, target)
  if (!any(mp$matched) || identical(mp$old, mp$new)) return(x)

  # Do not attempt a partial rename that would create duplicate seqlevels.
  if (any(duplicated(mp$new))) return(x)

  out <- tryCatch({
    GenomeInfoDb::seqlevels(x, pruning.mode = pruning.mode) <- mp$new
    x
  }, error = function(e1) {
    tryCatch({
      GenomeInfoDb::seqlevels(x) <- mp$new
      x
    }, error = function(e2) x)
  })

  out
}
